app/chat_engine/chat_engine/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('themes/', include('themes.urls')),
    path('hook/',include('github_hook.urls')),  
    path('ckeditor/',include('ckeditor_uploader.urls')),  
]

app/chat_engine/themes/urls.py
from django.urls import path, include
from . views import ThemesList, ThemeCreate, ThemeDelete, ThemeUpdate

app_name = "themes"

urlpatterns = [    
    path('create/',ThemeCreate.as_view(),name = 'create_theme'),
    path('delete/<pk>/',ThemeDelete.as_view(),name='delete_theme'),
    path('update/<pk>/',ThemeUpdate.as_view(),name='update_theme'),
    path('',ThemesList.as_view(),name='themes_list'),
]

app/chat_engine/templates/base.html
<!DOCTYPE html>
<html lang = "ru">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta http-equiv="X-UA-Compatible" content="ie=edge">
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
	<title>
		{% block title %}
			Chat Engine
		{% endblock %}
	</title>
</head>
<body>
	<nav class="navbar navbar-expand-sm bg-dark navbar-dark">	  
	  <div class="collapse navbar-collapse" id="navbarNavCollapse">
		<!-- Brand -->
  		<a class="navbar-brand" href="{% url 'themes:themes_list' %}">Logo</a>

	  	<!-- Links -->
	    <ul class="navbar-nav ml-auto">
	      <li class="nav-item">
	        <a class="nav-link" href="{% url 'themes:themes_list' %}">Конференции</a>
	      </li>
	      <!-- Dropdown -->
		  <li class="nav-item dropdown">
		    <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown">
		      Dropdown link
		    </a>
		    <div class="dropdown-menu">
		      <a class="dropdown-item" href="#">Link 1</a>
		      <a class="dropdown-item" href="#">Link 2</a>
		      <a class="dropdown-item" href="#">Link 3</a>
		    </div>
		  </li>
	      <li class="nav-item">
	      	  {% if request.user.is_authenticated %}
	      		<a class="nav-link" href="/accounts/logout/">Выйти</a>
	      		{% if request.user.first_name or request.user.last_name %}
                    {{ request.user.first_name }} {{ request.user.last_name }}
                {% else %}
                    {{ request.user.username }}
                {% endif %}
	      	  {% else %}
	      	  	<a class="nav-link" href="/accounts/login">Войти</a>
	      	  {% endif %}
          </li>	      
	    </ul>
	  </div>
	</nav>

	<div class="container">	
		<div class="row">
			<!-- Left Menu -->
			<div class="col-xs-3">
		<!--<ul class="nav flex-column">
				<li class="nav-item">
			    	<a class="nav-link" href="{% url 'themes:themes_list' %}">Главная</a>
				</li>	
			</ul> -->	
				<nav class = "navbar col-xs-3 col-md-4">
					<ul class="navbar-nav">
					    {% block left_menu %}
					
						{% endblock %}						    
					</ul>
				</nav>
			</div>
			<!-- Main Content -->	
			<div class="col mt-3">				
				 	{% block content %}
						There is no content
					{% endblock %}			
			</div>
		</div>
	</div>
</body>		
</html>