app/chat_engine/chat_engine/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('themes/', include('themes.urls')),
    path('hook/',include('github_hook.urls')),  
    path('ckeditor/',include('ckeditor_uploader.urls')),  
]

app/chat_engine/themes/urls.py
from django.urls import path, include
from . views import ThemesList, ThemeCreate, ThemeDelete, ThemeUpdate

app_name = "themes"

urlpatterns = [    
    path('create/',ThemeCreate.as_view(),name = 'create_theme'),
    path('delete/<pk>/',ThemeDelete.as_view(),name='delete_theme'),
    path('update/<pk>/',ThemeUpdate.as_view(),name='update_theme'),
    path('',ThemesList.as_view(),name='themes_list'),
]

app/chat_engine/themes/models.py
from django.db import models
from django.contrib.auth.models import User
from user.models import Profile

class Theme(models.Model):
	title = models.CharField(max_length=250, blank=False,null=False,verbose_name='Наименование')
	description = models.TextField(blank=True,verbose_name='Описание')
	author = models.ForeignKey(User,verbose_name="Автор",on_delete=models.PROTECT,limit_choices_to={'profile__is_teacher':True})
	pub_date = models.DateTimeField(auto_now_add=True,verbose_name="Дата публикации")

	# Profile.objects.filter(is_teacher=True)

	def __str__(self):
		return self.title

	class Meta:
		verbose_name = 'Тема конференции'
		verbose_name_plural = 'Темы конференции'
		ordering = ['-pub_date','author']

app/chat_engine/themes/forms.py
from django.forms import ModelForm
from . models import Theme

class ThemeForm(ModelForm):
	class Meta:
		model = Theme
		fields = '__all__'
		pass

app/chat_engine/themes/views.py
from django.shortcuts import render, get_object_or_404
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.views.generic import ListView
from django.views import View
from django.urls import reverse_lazy
from django.contrib.auth.models import User
from django.contrib.auth.mixins import UserPassesTestMixin
from . forms import ThemeForm
from user.models import Profile
from . models import Theme


class ThemesList(ListView):	
	template_name = 'themes/themes.html'
	model = Theme

class ThemeCreate(UserPassesTestMixin,CreateView):
	template_name = 'themes/create.html'
	form_class = ThemeForm
	success_url = reverse_lazy('themes:themes_list') 
	raise_exception = True

	def test_func(self):
		return not self.request.user.is_anonymous and self.request.user.profile.is_teacher

class ThemeDelete(UserPassesTestMixin,DeleteView):
	template_name = 'themes/delete.html'
	model = Theme
	success_url = reverse_lazy('themes:themes_list')
	raise_exception = True

	def test_func(self):
		return not self.request.user.is_anonymous and self.request.user.profile.is_teacher

class ThemeUpdate(UserPassesTestMixin,UpdateView):
	template_name = 'themes/create.html'
	model = Theme
	fields = ['title','description']
	success_url = reverse_lazy('themes:themes_list')
	raise_exception = True

	def test_func(self):
		return not self.request.user.is_anonymous and self.request.user.profile.is_teacher

app/chat_engine/templates/themes/create.html
{% extends 'base.html' %}
{% block title %}
	Тема (создание)
{% endblock %}

{% block content %}
	<form method="post">
		{% csrf_token %}
		{{ form.as_p }}
		<input type="submit" vаluе="Добавить">
	</form>
{% endblock %}

app/chat_engine/templates/themes/delete.html
{% extends 'base.html' %}
{% block title %}
	Тема (удаление)
{% endblock %}

{% block left_menu %}
	<li><a href="{% url 'themes:create_theme' %}">Создать</a></li>
{% endblock %}

{% block content %}
<h1>Тема "{{ object.title }}" (удаление)</h1>
<form action="" method="post">
	{% csrf_token %}	
    <p>Вы уверены, что хотите удалить конференцию "{{ object }}"?</p>
    <input type="submit" value="Удалить" />
</form>  
{% endblock %}

app/chat_engine/templates/themes/themes.html
{% extends 'base.html' %}
{% block title %}
	Темы
{% endblock %}

{% block left_menu %}
	{% if request.user.is_authenticated %}
	{% if request.user.profile.is_teacher %}
	<li><a href="{% url 'themes:create_theme' %}">Создать</a></li>
	{% endif %}
	{% endif %}
{% endblock %}

{% block content %}
  <div class="list-group">
  	{% for theme in object_list %}
		<a href="#" class="list-group-item list-group-item-action flex-column align-items-start mb-3">
			<div class="d-flex w-100 justify-content-between">
				<h5 class="mb-1">{{ theme.title }}</h5>
				<small>{{ theme.pub_date }}</small>
			</div>
			<p class="mb-1">{{ theme.description }}</p>
			<small class="text-muted">{{ theme.author }}</small>
		</a>
  	{% endfor %}  
</div>
{% endblock %}